service: people-manager-api

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline-sqs
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  environment: ${file(./environments.yml):environments.${self:custom.stage}}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-offline:
    httpPort: 3003
  dynamodb:
    start:
      port: 5000
      inMemory: true
      migrate: true
    stages:
      - ${self:custom.stage}
  serverless-offline-sqs:            
    apiVersion: '2012-11-05'
    endpoint: http://0.0.0.0:9324
    region: eu-west-1
    skipCacheInvalidation: false
    stages:
      - ${self:custom.stage}

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ${opt:region, 'eu-west-1'}
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: ${self:custom.environment.awsNodeJSConnectionReuseEnabled}
    PERSON_TABLE: Person-${self:custom.stage}
    DYNAMODB_CONN_URL: ${self:custom.environment.dynamodbUrl}
    PERSON_QUEUE: Person-${self:custom.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.PERSON_TABLE}"

functions:
  createPerson:
    handler: src/app/handlers/createPerson.handler
    events:
      - http:
          method: post
          path: person
          cors: true
  getAllPerson:
    handler: src/app/handlers/getAllPeople.handler
    events:
      - http:
          method: get
          path: all-people
          cors: true
  getPerson:
    handler: src/app/handlers/getPerson.handler
    events:
      - http:
          method: get
          path: person/{personId}
          cors: true
  updatePerson:
    handler: src/app/handlers/updatePerson.handler
    events:
      - http:
          method: put
          path: person/{personId}
          cors: true
  deletePerson:
    handler: src/app/handlers/deletePerson.handler
    events:
      - http:
          method: delete
          path: person/{personId}
          cors: true

  createPersonEventHandler:
    handler: src/app/handlers/personCreationEventHandler.queueHandler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - PersonQueue
              - Arn
              
resources:
  Resources:
    PersonListTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.PERSON_TABLE}
        AttributeDefinitions:
          - AttributeName: personId
            AttributeType: S
        KeySchema:
          - AttributeName: personId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    PersonQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: person-queue
